### ISSUE TITLE
Performace slow down with last release...

### ISSUE THREAD

**Issue by greg-double** [fabiospampinato/vscode-todo-plus#301]
Hi, I have found that since the last update the Todo+ extension has slowed down massively. Currently I have a todo file with 323 lines and it takes 1-3 secs to save add/edit a line. My previous todo list of 3990 lines takes 20+ seconds to make any edits. I have been using Todo+ for years. By the end of each year, each file is roughly the same size (4k lines) and until this last release performance was never an issue. 

My typical daily data looks like this...
![image](https://user-images.githubusercontent.com/55329854/106473991-6f392f00-6472-11eb-8f85-384112354485.png)

**Comment by dwolff** [comment]
@fabiospampinato I've compared the latest version (4.18.2) with the one before that (4.18.1), here: https://github.com/fabiospampinato/vscode-todo-plus/compare/v4.18.1...v4.18.2

It looks like the only change made here was in the item "projectParts" in "src/const.ts". I can confirm that this is the reason of the slow response time that @greg-double is mentioning.

Big fan of this extension as well! Keep up the good work!

**Comment by dwolff** [comment]
@greg-double you can use the older version (4.18.1), it works without the "slow" issue. I can confirm that. Just go to the list of installed extensions, open the context menu and select the option "Install Another Version..." and then choose the 4.18.1 one.

**Comment by greg-double** [comment]
Perfect, thank you very much!


*Azure Cloud Solution Architect | *gdouble@etak.ca | 905.484.0331 | etak.ca
Cloud strategies are becoming more vital and complex. Cloud architects play
a crucial role in helping organizations avoid risk, manage costs and ensure
a successful, cost-effective transition to the cloud.

**Comment by Gander7** [comment]
Thank you! Can't have a file with more than 100 lines without starting to get lag with latest version.

**Comment by fabiospampinato** [comment]
I've looked into this, the problematic commit in question just deleted one character from one regex, but I don't understand how this is causing the performa issue you guys are seeing.

Can somebody send me a file that reproduces the issue?

**Comment by fabiospampinato** [comment]
I pushed a new release, which may address this issue, it would be useful if somebody who experienced the slowdown can check that.

**Comment by dwolff** [comment]
@fabiospampinato looks like (at least to me) that the fix is working well! I've updated to the latest version (4.18.3) and I don't see the performance issue. 

Thanks!

**Comment by fabiospampinato** [comment]
@dwolff Nice, thanks for checking! Would it be possible for you to send me a .todo file that reproduced the slowdown issue with the previous version? I would still like to understand why that single character deletion caused issues.

**Comment by NotWearingPants** [comment]
@fabiospampinato This is still an issue for me with the latest release (4.18.4)

To reproduce, open an empty .todo file and copy-and-paste the following about 50 times (or more depending on how good your computer is):
```
a:
	☐ a
```
And make sure to use **tabs** rather than spaces for the indentation.
Now go to one of the items and toggle its checkbox with Ctrl+Enter repeatedly, this should be pretty slow (about a second per toggle).

This slowdown only happens to me with tabs for some reason. Probably because only tabs cause the extension to show the number of items next to the header in brackets. I wonder if the other people here used tabs as well 🤔
